proto_library(
    name = "google_rpc_proto",
    srcs = glob(["**/*.proto"]),
    deps = [
        "@com_google_protobuf//:any_proto",
        "@com_google_protobuf//:duration_proto",
    ],
    visibility = ["//visibility:public"],
)    
